import properties from './properties';
import { Platform } from 'react-native';


export const ICON = {
  back: require('assets/icon/icon-back.png'),
  job: require('assets/icon/icon-job.png'),
  degree: require('assets/icon/icon-degree.png'),
  income: require('assets/icon/icon-income.png'),
  asset: require('assets/icon/icon-asset.png'),
  sns: require('assets/icon/icon-sns.png'),
  vehicle: require('assets/icon/icon-vehicle.png'),
  jobNew: require('assets/icon/icon-job-new.png'),
  degreeNew: require('assets/icon/icon-degree-new.png'),
  incomeNew: require('assets/icon/icon-income-new.png'),
  assetNew: require('assets/icon/icon-asset-new.png'),
  snsNew: require('assets/icon/icon-sns-new.png'),
  vehicleNew: require('assets/icon/icon-vehicle-new.png'),
  arrRight: require('assets/icon/icon-arr-right.png'),
  arrRight02: require('assets/icon/icon-arr-right02.png'),
  arrLeft02: require('assets/icon/icon-arr-left02.png'),
  arrBottom: require('assets/icon/icon-arrow-bottom.png'),
  xBtn: require('assets/icon/icon-x.png'),
  xBtn2: require('assets/icon/icon-x2.png'),
  xBtn3: require('assets/icon/icon-x3.png'),
  plus: require('assets/icon/icon-plus.png'),
  plus2: require('assets/icon/icon-plus2.png'),
  distance: require('assets/icon/icon-distance.png'),
  close: require('assets/icon/icon-close.png'),
  like: require('assets/icon/icon-like.png'),
  royalpass: require('assets/icon/icon-royalpass.png'),
  tooltip: require('assets/icon/icon-tooltip.png'),
  siren: require('assets/icon/icon-siren.png'),
  party: require('assets/icon/icon-party.png'),
  checkOff: require('assets/icon/icon-check-off.png'),
  checkOn: require('assets/icon/icon-check-on.png'),
  star: require('assets/icon/icon-star.png'),
  starHalf: require('assets/icon/icon-star-half.png'),
  starEmpty: require('assets/icon/icon-star-empty.png'),
  starNew: require('assets/icon/icon-star-new.png'),
  starHalfNew: require('assets/icon/icon-star-half-new.png'),
  starEmptyNew: require('assets/icon/icon-star-empty-new.png'),
  starBlack: require('assets/icon/icon-star-black.png'),
  starWhite: require('assets/icon/icon-star-white.png'),
  starYellow: require('assets/icon/icon-star-yellow.png'),
  new: require('assets/icon/icon-new.png'),
  badge: require('assets/icon/icon-badege.png'),
  process: require('assets/icon/icon-process.png'),
  search: require('assets/icon/icon-search.png'),
  pen: require('assets/icon/icon-pen.png'),
  penGray: require('assets/icon/icon-pen-gray.png'),
  kakao: require('assets/icon/icon-kakao.png'),
  wait: require('assets/icon/icon-wait.png'),
  pass: require('assets/icon/icon-pass.png'),
  currency: require('assets/icon/icon-currency.png'),
  ticket: require('assets/icon/icon-ticket.png'),  
  roundCrown: require('assets/icon/icon-round-crown.png'),
  delevery: require('assets/icon/icon-delevery.png'),
  crown: require('assets/icon/icon-crown.png'),
  closeBlack: require('assets/icon/icon-close-black.png'),
  limited_on: require('assets/icon/limited_on.png'),
  limited_off_white: require('assets/icon/limited_off_white.png'),
  limited_off_gray: require('assets/icon/limited_off_gray.png'),
  live_on: require('assets/icon/live_on.png'),
  live_off_white: require('assets/icon/live_off_white.png'),
  live_off_gray: require('assets/icon/live_off_gray.png'),
  arrow_right: require('assets/icon/arrow_right.png'),
  plus_primary: require('assets/icon/plus.png'),
  plus_gray: require('assets/icon/plus_gray.png'),
  icon_smile: require('assets/icon/icon_smail.png'),
  confirmation: require('assets/icon/confirmation.png'),
  match_succ_icon: require('assets/icon/match_succ_icon.png'),
  passIconNew: require('assets/icon/pass_icon_new.png'),
  royalPassIconNew: require('assets/icon/loyalpass_icon_new.png'),
  passCircle: require('assets/icon/passCircle.png'),
  royalPassCircle: require('assets/icon/royalPassCircle.png'),
  zzimCircle: require('assets/icon/zzimCircle.png'),
  inventoryIcon: require('assets/icon/inventory_icon.png'),
  refuseJobIcon: require('assets/icon/refuse_job_icon.png'),
  refuseAssetIcon: require('assets/icon/refuse_asset_icon.png'),
  refuseEduIcon: require('assets/icon/refuse_edu_icon.png'),
  refuseSnsIcon: require('assets/icon/refuse_sns_icon.png'),
  refuseVehicleIcon: require('assets/icon/refuse_vehicle_icon.png'),
  refuseIncomeIcon: require('assets/icon/refuse_income_icon.png'),
  refuseMaleIcon: require('assets/icon/refuse_male_icon.png'),
  refuseFemaleIcon: require('assets/icon/refuse_female_icon.png'),
  question: require('assets/icon/icon-question.png'),
  level10Icon: require('assets/icon/level_10_icon.png'),
  level15Icon: require('assets/icon/level_15_icon.png'),
  level20Icon: require('assets/icon/level_20_icon.png'),
  level25Icon: require('assets/icon/level_25_icon.png'),
  level30Icon: require('assets/icon/level_30_icon.png'),
  scoreDiamondIcon: require('assets/icon/score_diamond_icon.png'),
  scoreKingIcon: require('assets/icon/score_king_icon.png'),
  zzimIcon: require('assets/icon/zzim_icon.png'),
  loveLetterIcon: require('assets/icon/icon-love-letter.png'),
  playIcon: require('assets/icon/play_icon.png'),
  dottedIcon: require('assets/icon/dotted_icon.png'),
  checkOnIcon: require('assets/icon/check_on.png'),
  checkOffIcon: require('assets/icon/check_off.png'),
  loveIcon: require('assets/icon/love_icon.png'),
  boxTipsIcon: require('assets/icon/box_tips_icon.png'),
  giftIcon: require('assets/icon/gift_icon.png'),
  logoTransIcon: require('assets/icon/logo_trans_icon.png'),
  xBlueIcon: require('assets/icon/x_blue_icon.png'),
  xRedIcon: require('assets/icon/x_red_icon.png'),
  saleIcon: require('assets/icon/sale_icon.png'),
  bellIcon: require('assets/icon/bell_icon.png'),
  nextArrowIcon: require('assets/icon/next_arrow_icon.png'),
  celebrityIcon01: require('assets/icon/celebrity_icon01.png'),
  celebrityIcon02: require('assets/icon/celebrity_icon02.png'),
  celebrityIcon03: require('assets/icon/celebrity_icon03.png'),
  celebrityIcon04: require('assets/icon/celebrity_icon04.png'),
  celebrityIcon05: require('assets/icon/celebrity_icon05.png'),
  celebrityIcon06: require('assets/icon/celebrity_icon06.png'),
  secret: require('assets/icon/icon-secret.png'),
  mail: require('assets/icon/icon-mail.png'),
  mailGold: require('assets/icon/icon-mail-gold.png'),
  megaphone: require('assets/icon/icon-megaphone.png'),
  closeLight: require('assets/icon/icon-close-light.png'),
  storyHeart: require('assets/icon/icon-story-heart.png'),
  reply: require('assets/icon/icon-reply.png'),
  clockIcon: require('assets/icon/icon-clock.png'),
  storyPlusIcon: require('assets/icon/icon-story-plus.png'),
  heartOffIcon: require('assets/icon/icon-heart-off.png'),
  heartOnIcon: require('assets/icon/icon-heart-on.png'),
  modfyIcon: require('assets/icon/icon-modfy.png'),
  storyNoIcon: require('assets/icon/icon-story-no.png'),
  betaWhiteIcon: require('assets/icon/icon-beta-white.png'),
  betaBlueIcon: require('assets/icon/icon-beta-blue.png'),
  betaGrayIcon: require('assets/icon/icon-beta-gray.png'),
  talkBalloonIcon: require('assets/icon/icon-talk-balloon.png'),
  talkQuestionIcon: require('assets/icon/icon-talk-question.png'),
  voteIcon: require('assets/icon/icon-vote.png'),
  maleIcon: require('assets/icon/icon-male.png'),
  femaleIcon: require('assets/icon/icon-female.png'),
  confetti: require('assets/icon/confetti.png'),
  storySecretIcon: require('assets/icon/icon-story-secret.png'),
  bookmarkBlack: require('assets/icon/icon-bookmark-black.png'),
  bookmarkPurple: require('assets/icon/icon-bookmark-purple.png'),
  bookmarkWhite: require('assets/icon/icon-bookmark-white.png'),
  murtipleImage: require('assets/icon/icon-murtiple-image.png'),
  speechDotline: require('assets/icon/icon-speech-dotline.png'),
  speechQuestion: require('assets/icon/icon-speech-question.png'),
  storyMale: require('assets/icon/icon-story-male.png'),
  storyFemale: require('assets/icon/icon-story-female.png'),
  padlockMale: require('assets/icon/icon-padlock-male.png'),
  padlockFemale: require('assets/icon/icon-padlock-female.png'),
  pickWhite: require('assets/icon/icon-pick-white.png'),
  pickPurple: require('assets/icon/icon-pick-purple.png'),
  circleX: require('assets/icon/icon-circle-x.png'),
  digitalClock: require('assets/icon/icon-digital-clock.png'),
  authAsset: require('assets/icon/icon-auth-asset.png'),
  authEdu: require('assets/icon/icon-auth-edu.png'),
  authJob: require('assets/icon/icon-auth-job.png'),
  authIncome: require('assets/icon/icon-auth-income.png'),
  authSns: require('assets/icon/icon-auth-sns.png'),
  authVehicle: require('assets/icon/icon-auth-vehicle.png'),
  checkYellow: require('assets/icon/icon-check-yellow.png'),
  checkGold: require('assets/icon/icon-check-gold.png'),
  xYellow: require('assets/icon/icon-x-yellow.png'),
  userAdd: require('assets/icon/icon-user-add.png'),
  userPen: require('assets/icon/icon-user-pen.png'),
  commentYellow: require('assets/icon/icon-comment-yellow.png'),
  commentRed: require('assets/icon/icon-comment-red.png'),
  cloudUpload: require('assets/icon/icon-cloud-upload.png'),
  searchYellow: require('assets/icon/icon-search-yellow.png'),
  bellYellow: require('assets/icon/icon-bell-yellow.png'),
  moneyBill: require('assets/icon/icon-money-bill.png'),
  cardGold: require('assets/icon/icon-card-gold.png'),
  radioYellow: require('assets/icon/icon-radio-yellow.png'),
  squarePen: require('assets/icon/icon-square-pen.png'),
  sirenMark: require('assets/icon/icon-siren-mark.png'),
  hifive: require('assets/icon/icon-hifive.png'),
  heartFace: require('assets/icon/icon-heart-face.png'),
  polygonGreen: require('assets/icon/icon-polygon-green.png'),
  passSquare: require('assets/icon/icon-pass-square.png'),
  circleArrow: require('assets/icon/icon-circle-arrow.png'),
  arrowLeftBrown: require('assets/icon/icon-arrow-left-brown.png'),
  profileYellow: require('assets/icon/icon-profile-yellow.png'),
  profileGray: require('assets/icon/icon-profile-gray.png'),
  bellGold: require('assets/icon/icon-bell-gold.png'),
  bellGray: require('assets/icon/icon-bell-gray.png'),
  cartYellow: require('assets/icon/icon-cart-yellow.png'),
  cartGray: require('assets/icon/icon-cart-gray.png'),
  sparkler: require('assets/icon/icon-sparkler.png'),
  reportBtn: require('assets/icon/icon-report_btn.png'),
  cardCyan: require('assets/icon/icon-card-cyan.png'),
  cardGray: require('assets/icon/icon-card-gray.png'),
  drinkCyan: require('assets/icon/icon-drink-cyan.png'),
  drinkGray: require('assets/icon/icon-drink-gray.png'),
  dotCyan: require('assets/icon/icon-dot-cyan.png'),
  dotGray: require('assets/icon/icon-dot-gray.png'),
  polygonGray: require('assets/icon/icon-polygon-gray.png'),
  megaCubeCyan: require('assets/icon/icon-megacube-cyan.png'),
  cubeCyan: require('assets/icon/icon-cube-cyan.png'),
  cubeYCyan: require('assets/icon/icon-cube-y-cyan.png'),
  menuCyan: require('assets/icon/icon-menu-cyan.png'),
  naverLogo: require('assets/icon/icon-naver-logo.png'),
  circleS: require('assets/icon/icon-circle-s.png'),
  circleA: require('assets/icon/icon-circle-a.png'),
  circleB: require('assets/icon/icon-circle-b.png'),
  circleC: require('assets/icon/icon-circle-c.png'),
  circleD: require('assets/icon/icon-circle-d.png'),
  circleE: require('assets/icon/icon-circle-e.png'),
  circleComplete: require('assets/icon/icon-circle-complete.png'),
  circleUnrank: require('assets/icon/icon-circle-unrank.png'),
  starGray: require('assets/icon/icon-star-gray.png'),
  starCyan: require('assets/icon/icon-star-cyan.png'),
  paiksLogo: require('assets/icon/icon-paiks-logo.png'),
  starbucksLogo: require('assets/icon/icon-starbucks-logo.png'),
  baskinLogo: require('assets/icon/icon-baskin-logo.png'),
  twosomeLogo: require('assets/icon/icon-twosome-logo.png'),
  megaLogo: require('assets/icon/icon-mega-logo.png'),
  daisoLogo: require('assets/icon/icon-daiso-logo.png'),
  cuLogo: require('assets/icon/icon-cu-logo.png'),
  gift: require('assets/icon/icon-gift.png'),
  icChip: require('assets/icon/icon-ic-chip.png'), 
  yBlue: require('assets/icon/icon-y-blue.png'),
  certificate: require('assets/icon/icon-certificate.png'),
  penSquare: require('assets/icon/icon-pen-square.png'),
  circleReward: require('assets/icon/icon-circle-reward.png'),
  chatRed: require('assets/icon/icon-chat-red.png'),
  cardBlack: require('assets/icon/icon-card-black.png'),
  blindDetail: require('assets/icon/icon-blind-detail.png'),
  replayBlack: require('assets/icon/icon-replay-black.png'),




  /* common */
  commonSelect: require('assets/icon/common/select_icon.png'),
  selectDown: require('assets/icon/common/select_down.png'),
  backBtnType01: require('assets/icon/common/back_btn_type_01.png'),
  declaration: require('assets/icon/common/declaration_icon.png'),
  searchWhite: require('assets/icon/common/search_white.png'),
  orderIcon: require('assets/icon/common/order_icon.png'),
  settingIcon: require('assets/icon/common/setting_icon.png'),
  cube: require('assets/icon/common/cube.png'),
  megaCube: require('assets/icon/common/mega_cube.png'),
  checkWhite: require('assets/icon/common/check_white.png'),
  popupDown: require('assets/icon/common/popup_down.png'),
  print: require('assets/icon/common/print.png'),
  alertRed: require('assets/icon/common/alert_red.png'),
  intro: require('assets/icon/common/intro.png'),
  wifi: require('assets/icon/common/wifi.png'),
  closeBtn: require('assets/icon/common/close_btn.png'),
  closeBtnWhite: require('assets/icon/common/close_btn_white.png'),
  boardEvent: require('assets/icon/common/board_event.png'),
  boardGuide: require('assets/icon/common/board_guide.png'),
  boardNotice: require('assets/icon/common/board_notice.png'),
  navContents: require('assets/icon/common/nav_contents.png'),
  navContentsOn: require('assets/icon/common/nav_contents_on.png'),
  navStory: require('assets/icon/common/nav_story.png'),
  navStoryOn: require('assets/icon/common/nav_story_on.png'),
  navStorage: require('assets/icon/common/nav_storage.png'),
  navStorageOn: require('assets/icon/common/nav_storage_on.png'),
  navShop: require('assets/icon/common/nav_shop.png'),
  navShopOn: require('assets/icon/common/nav_shop_on.png'),
  dropDown: require('assets/icon/common/drop_down.png'),
  dropUp: require('assets/icon/common/drop_up.png'),
  editBtn: require('assets/icon/common/edit_btn.png'),
  writeBtn: require('assets/icon/common/write_btn.png'),
  checkGreenIcon: require('assets/icon/common/check_green_icon.png'),
  arrowRight: require('assets/icon/common/arrow_right.png'),
  searchGreen: require('assets/icon/common/search_green.png'),
  respectIcon: require('assets/icon/common/respect_icon.png'),
  addWhite: require('assets/icon/common/add_white.png'),
  pencilBlue: require('assets/icon/common/pencil_blue.png'),
  checkBlue: require('assets/icon/common/check_blue.png'),

  /* match */
  distanceIcon: require('assets/icon/match/distance_icon.png'),
  sendIcon: require('assets/icon/match/send_icon.png'),
  moreIcon: require('assets/icon/match/more_icon.png'),
  homeIcon: require('assets/icon/match/home_icon.png'),
  refuseIcon: require('assets/icon/match/refuse_icon.png'),
  phoneIcon: require('assets/icon/match/phone_icon.png'),
  lockIcon: require('assets/icon/match/lock_icon.png'),
  storageEmptyFemale: require('assets/icon/match/storage_empty_female.png'),
  storageEmptyMale: require('assets/icon/match/storage_empty_male.png'),
  chatIcon: require('assets/icon/match/chat_icon.png'),
  chatOutIcon: require('assets/icon/match/chat_out_icon.png'),


  /* auth */
  jobIcon: require('assets/icon/auth/job_icon.png'),
  eduIcon: require('assets/icon/auth/edu_icon.png'),
  incomeIcon: require('assets/icon/auth/income_icon.png'),
  assetIcon: require('assets/icon/auth/asset_icon.png'),
  snsIcon: require('assets/icon/auth/sns_icon.png'),
  vehicleIcon: require('assets/icon/auth/vehicle_icon.png'),
  bankIcon: require('assets/icon/auth/bank_icon.png'),
  realtyIcon: require('assets/icon/auth/realty_icon.png'),
  auth_mark: require('assets/icon/auth/auth_mark.png'),
  auth_itemJob: require('assets/icon/auth/item_job.png'),
  auth_itemEdu: require('assets/icon/auth/item_edu.png'),
  auth_itemAsset: require('assets/icon/auth/item_asset.png'),
  auth_itemIncome: require('assets/icon/auth/item_income.png'),
  auth_itemSns: require('assets/icon/auth/item_sns.png'),

  /* vibe */
  vibeEmpty: require('assets/icon/vibe/vibe_empty.png'),

  /* member */
  drinkingIcon: require('assets/icon/member/drinking_icon.png'),
  mbtiIcon: require('assets/icon/member/mbti_icon.png'),
  religionIcon: require('assets/icon/member/religion_icon.png'),
  smokeIcon: require('assets/icon/member/smoke_icon.png'),
  member_body: require('assets/icon/member/member_body.png'),
  member_length: require('assets/icon/member/member_length.png'),
  member_suitcase: require('assets/icon/member/member_suitcase.png'),
  member_drink: require('assets/icon/member/member_drink.png'),
  member_interest: require('assets/icon/member/member_interest.png'),
  member_interview: require('assets/icon/member/member_interview.png'),
  member_local: require('assets/icon/member/member_local.png'),
  member_mbti: require('assets/icon/member/member_mbti.png'),
  member_religion: require('assets/icon/member/member_religion.png'),
  member_smoke: require('assets/icon/member/member_smoke.png'),
  int_body: require('assets/icon/member/int_body.png'),
  int_entertainment: require('assets/icon/member/int_entertainment.png'),
  int_lifestyle: require('assets/icon/member/int_lifestyle.png'),
  int_social: require('assets/icon/member/int_social.png'),
  int_active: require('assets/icon/member/int_active.png'),
  int_food: require('assets/icon/member/int_food.png'),
  int_game: require('assets/icon/member/int_game.png'),
  int_leisure: require('assets/icon/member/int_leisure.png'),
  saveIcon: require('assets/icon/member/save_icon.png'),

  /* myhome */
  alarm: require('assets/icon/myhome/alarm.png'),
  menu: require('assets/icon/myhome/menu.png'),
  myhomeTopBg: require('assets/icon/myhome/myhome_top_bg.png'),
  respectCube: require('assets/icon/myhome/respect_cube.png'),
  respectMegaCube: require('assets/icon/myhome/respect_mega_cube.png'),
  respectFree: require('assets/icon/myhome/respect_free.png'),
  awardLeft: require('assets/icon/myhome/award_left.png'),
  awardRight: require('assets/icon/myhome/award_right.png'),
  peapleIcon: require('assets/icon/myhome/peaple_icon.png'),
  authLevel: require('assets/icon/myhome/auth_level.png'),
  grade01: require('assets/icon/myhome/grade_01.png'),
  grade02: require('assets/icon/myhome/grade_02.png'),
  grade03: require('assets/icon/myhome/grade_03.png'),
  grade04: require('assets/icon/myhome/grade_04.png'),
  grade05: require('assets/icon/myhome/grade_05.png'),
  grade06: require('assets/icon/myhome/grade_06.png'),

  /* story */
  story_heartBlack: require('assets/icon/story/heart_black.png'),
  story_heartWhite: require('assets/icon/story/heart_white.png'),
  story_heartWhiteFill: require('assets/icon/story/heart_white_fill.png'),
  story_replyBlack: require('assets/icon/story/reply_black.png'),
  story_replyWhite: require('assets/icon/story/reply_white.png'),
  story_write: require('assets/icon/story/write.png'),
  story_starOff: require('assets/icon/story/star_off.png'),
  story_starOn: require('assets/icon/story/star_on.png'),
  story_regTmp: require('assets/icon/story/reg_tmp.png'),
  story_imageRegi: require('assets/icon/story/image_regi.png'),
  story_moreAdd: require('assets/icon/story/more_add.png'),
  story_calculator: require('assets/icon/story/calculator.png'),
  story_promptN: require('assets/icon/story/prompt_n.png'),
  story_promptY: require('assets/icon/story/prompt_y.png'),
  story_promptNRed: require('assets/icon/story/prompt_n_red.png'),
  story_promptYGreen: require('assets/icon/story/prompt_y_green.png'),
  story_people: require('assets/icon/story/people.png'),
  story_minusCircle: require('assets/icon/story/minus_circle.png'),
  story_plusCircle: require('assets/icon/story/plus_circle.png'),
  story_tag: require('assets/icon/story/tag.png'),
  story_lock: require('assets/icon/story/lock.png'),
  story_upBtn: require('assets/icon/story/up_btn.png'),
  story_downBtn: require('assets/icon/story/down_btn.png'),
  story_man01: require('assets/icon/story/man_01.png'),
  story_man02: require('assets/icon/story/man_02.png'),
  story_woman01: require('assets/icon/story/woman_01.png'),
  story_woman02: require('assets/icon/story/woman_02.png'),

  story_manPeople01: require('assets/icon/story/man_people_01.png'),
  story_manPeople02: require('assets/icon/story/man_people_02.png'),
  story_manPeople03: require('assets/icon/story/man_people_03.png'),
  story_manPeople04: require('assets/icon/story/man_people_04.png'),
  story_manPeople05: require('assets/icon/story/man_people_05.png'),
  story_manPeople06: require('assets/icon/story/man_people_06.png'),
  story_manPeople07: require('assets/icon/story/man_people_07.png'),
  story_manPeople08: require('assets/icon/story/man_people_08.png'),
  story_womanPeople01: require('assets/icon/story/woman_people_01.png'),
  story_womanPeople02: require('assets/icon/story/woman_people_02.png'),
  story_womanPeople03: require('assets/icon/story/woman_people_03.png'),
  story_womanPeople04: require('assets/icon/story/woman_people_04.png'),
  story_womanPeople05: require('assets/icon/story/woman_people_05.png'),
  story_womanPeople06: require('assets/icon/story/woman_people_06.png'),
  story_womanPeople07: require('assets/icon/story/woman_people_07.png'),
  story_womanPeople08: require('assets/icon/story/woman_people_08.png'),


  /* shop */
  shop_inventory: require('assets/icon/shop/inventory.png'),
  shop_femaleShop: require('assets/icon/shop/female_shop.png'),
  shop_tabCubeOn: require('assets/icon/shop/tab_cube_on.png'),
  shop_tabCubeOff: require('assets/icon/shop/tab_cube_off.png'),
  shop_tabMegaOn: require('assets/icon/shop/tab_mega_on.png'),
  shop_tabMegaOff: require('assets/icon/shop/tab_mega_off.png'),
  shop_tabCardOn: require('assets/icon/shop/tab_card_on.png'),
  shop_tabCardOff: require('assets/icon/shop/tab_card_off.png'),
  shop_tabBoostOn: require('assets/icon/shop/tab_boost_on.png'),
  shop_tabBoostOff: require('assets/icon/shop/tab_boost_off.png'),
  shop_tabPackageOn: require('assets/icon/shop/tab_package_on.png'),
  shop_tabPackageOff: require('assets/icon/shop/tab_package_off.png'),
  shop_tabAllOn: require('assets/icon/shop/tab_all_on.png'),
  shop_tabAllOff: require('assets/icon/shop/tab_all_off.png'),
  shop_productCube: require('assets/icon/shop/product_cube.png'),
  shop_productMega: require('assets/icon/shop/product_mega.png'),
  shop_productCard: require('assets/icon/shop/product_card.png'),
  shop_productBoost: require('assets/icon/shop/product_boost.png'),
  shop_productPackage: require('assets/icon/shop/product_package.png'),
  shop_download: require('assets/icon/shop/download.png'),
  shop_inventoryNoimg: require('assets/icon/shop/inventory_noimg.png'),
  shop_order: require('assets/icon/shop/order.png'),
  shop_rpCard: require('assets/icon/shop/rp_card.png'),
  shop_rpBanner: require('assets/icon/shop/rp_banner.png'),
  shop_brandAll: require('assets/icon/shop/brand_all.png'),
  shop_refresh: require('assets/icon/shop/refresh.png'),
  shop_maleBg: require('assets/icon/shop/male_bg.png'),

  /* join */
  join_bg: require('assets/icon/join/bg.png'),
  join_imgSelect: require('assets/icon/join/img_select.png'),
  join_close: require('assets/icon/join/close.png'),
  join_exclamation: require('assets/icon/join/exclamation.png'),

  /* scenario */
  scenario_datingImg: require('assets/icon/scenario/dating_img.png'),
  scenario_bgImg: require('assets/icon/scenario/bg_img.png'),
  scenario_descIcon1: require('assets/icon/scenario/desc_icon1.png'),
  scenario_descIcon2: require('assets/icon/scenario/desc_icon2.png'),
  scenario_descIcon3: require('assets/icon/scenario/desc_icon3.png'),
  scenario_play: require('assets/icon/scenario/play.png'),
  scenario_heartYellow: require('assets/icon/scenario/heart_yellow.png'),


};

export const GIF_IMG = {
  faceScan: require('assets/img/gif/face-scan.gif'),
  loading: require('assets/img/gif/loading.gif'),
  soon: require('assets/img/gif/loading_icon.gif'),
  loadingIcon: require('assets/img/gif/loading_icon_2.gif'),
  loadingNewIcon: require('assets/img/gif/loading_new.gif'),
};

export const IMAGE = {
  logoIcon: require('assets/img/logo_icon.png'),
  logoIcon03: require('assets/img/logo_icon03.png'),
  logoStoryBox: require('assets/img/logo_story_box.png'),
  signImg: require('assets/img/sign_img.png'),
  heartImg01: require('assets/img/heart_img.png'),
  logoLeap: require('assets/img/logo_leap.png'),
  logoLeapTmon: require('assets/img/logo_leap_tmon.png'),
  logoLeapTit: require('assets/img/logo_leap_tit.png'),
  logoLeapTit02: require('assets/img/logo_leap_tit02.png'),
  storySecretMale: require('assets/img/story_secret_male.png'),
  storySecretFemale: require('assets/img/story_secret_female.png'),
};

export const PROFILE_IMAGE = {
  manTmp1: require('assets/img/tmp/profile_m_01.jpg'),
  womanTmp1: require('assets/img/tmp/profile_w_01.jpg'),
};

export const GUIDE_IMAGE = {
  daily01Thumnail: require('assets/img/guide/daily_01_thumnail.png'),
  daily01Content: require('assets/img/guide/daily_01_content.png'),
  daily02Content: require('assets/img/guide/daily_02_content.png'),
  daily03Content: require('assets/img/guide/daily_03_content.png'),
  live01Thumnail: require('assets/img/guide/live_01_thumnail.png'),
  live02Thumnail: require('assets/img/guide/live_02_thumnail.png'),
  live03Thumnail: require('assets/img/guide/live_03_thumnail.png'),
  robyThumnail: require('assets/img/guide/roby_thumnail.png'),
  roby01Content: require('assets/img/guide/roby_01_content.png'),
  roby02Content: require('assets/img/guide/roby_02_content.png'),
  roby03Content: require('assets/img/guide/roby_03_content.png'),
  profile01Img: require('assets/img/guide/profile_01_img.png'),
  profile02Img: require('assets/img/guide/profile_02_img.png'),
  profile03Img: require('assets/img/guide/profile_03_img.png'),
  shop01ContentBasic: require('assets/img/guide/shop_01_content_basic.png'),
  shop01ContentBoosting: require('assets/img/guide/shop_01_content_boosting.png'),
  shop01ContentPackage: require('assets/img/guide/shop_01_content_package.png'),
  shop02Content: require('assets/img/guide/shop_02_content.png'),
  shop03Content: require('assets/img/guide/shop_03_content.png'),
  robyProfile01Content: require('assets/img/guide/roby_profile_01_content.png'),
  robyProfile02Content: require('assets/img/guide/roby_profile_02_content.png'),
  robyGrade01Content: require('assets/img/guide/roby_grade_01_content.png'),
  robyGrade02Content: require('assets/img/guide/roby_grade_02_content.png'),
  robyGrade03Content: require('assets/img/guide/roby_grade_03_content.png'),
  storageContent: require('assets/img/guide/storage_content.png'),
};



export function findSourcePath(img_file_path: any) {
  if (img_file_path) {
    if (img_file_path.startsWith('http') || img_file_path.startsWith('file:///') || img_file_path.startsWith('/Users') || img_file_path.startsWith('/Devices') || img_file_path.startsWith('/Application')) {
      return { uri: img_file_path };
    } else {
      const path = properties.img_domain + img_file_path;
      return { uri: path };
    }
  }
  return img_file_path;
}

export function findSourcePathLocal(img_file_path: any) {
  if (img_file_path) {
    if (img_file_path.startsWith('http')) {
      return { uri: img_file_path };
    } else if (img_file_path.startsWith('file:///')) {
      return { uri: img_file_path };
    } else {
      const path = properties.local_img_domain + img_file_path;
      return { uri: path };
    }
  }
  return img_file_path;
}
